/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.user;

import controllers.user.UserController;
import controllers.user.UserInterface;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utils.CustomInternalJFrame;

/**
 *
 * @author jenif
 */
public class FrmAllUsers extends javax.swing.JInternalFrame {

    private UserInterface service;
    CustomInternalJFrame customizer;
    DefaultTableModel dtm = new DefaultTableModel();

    public FrmAllUsers() throws SQLException {
        initComponents();
        service = new UserController();
        String[] titulo = new String[]{"Usuario", "Contraseña", "Identificacion", "Nombre",
            "Apellidos", "Email", "Telefono", "Direccion", "Nacimiento"};
        dtm.setColumnIdentifiers(titulo);//Le agrega el los titulos a las columnas
        tbUser.setModel(dtm);
        customizer = new CustomInternalJFrame();
        customizer.setOpacity(this, 180);
        customizer.setEliminatedBorder(this);
        customizer.enableDrag(this);

        JTableHeader header = tbUser.getTableHeader();
        header.setBackground(new Color(141, 67, 240));// Cambiar color de fondo
        header.setFont(new Font("Segoe UI", Font.BOLD, 12));
        header.setForeground(Color.WHITE);

        // Alineación central del texto en el encabezado
        //DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) tbUser.getTableHeader().getDefaultRenderer();
        //headerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        txtGetAll = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();

        btnReturn.setBackground(new java.awt.Color(141, 67, 240));
        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Regresar");
        btnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        txtGetAll.setBackground(new java.awt.Color(141, 67, 240));
        txtGetAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGetAll.setForeground(new java.awt.Color(255, 255, 255));
        txtGetAll.setText("Mostrar Datos");
        txtGetAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetAllActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitle.setText("Lista de Usuarios");

        jScrollPane.setColumnHeaderView(null);

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tbUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(txtGetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(lbTitle)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGetAll)
                    .addComponent(btnReturn))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetAllActionPerformed
        // TODO add your handling code here:
        if (getAll()) {
            txtGetAll.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Estos son todos los resgitros", "Message", 1);
        }
    }//GEN-LAST:event_txtGetAllActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        clearTable();
        txtGetAll.setEnabled(true);//habilita el boton de mostrar datos
    }//GEN-LAST:event_btnReturnActionPerformed

    private boolean getAll() {
        String data[][] = service.list();
        if (data != null) {
            for (String[] usuario : data) {
                dtm.addRow(usuario);
            }
            return true;
        }

        return false;
    }

    private void clearTable() {
        dtm.setRowCount(0); //limpia el contenido de una tabla
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable tbUser;
    private javax.swing.JButton txtGetAll;
    // End of variables declaration//GEN-END:variables
}
